#RANDOM NUMBER DATASET GENERATOR
#version 1.4
#by Amlan Saha Kundu
#FunWithPython --- Day 3, Hour 4.

#===================================================================================================================================================================================
import os, sys,time
from time import strftime

#Welcome User :) -------------------------------------------------------------------------------------------------------------------------------------------------------------------
print('Enter your name :')
user = input()
print('\n Hi '+ user + ' ! \n')
print(' '+'='*50+'\n'+' Welcome to RANDOM NUMBER DATASET GENERATOR v1.4'+'\n'+' '+'='*50+'\n ')

#Input no. of data set want & size of each dataset----------------------------------------------------------------------------------------------------------------------------------
print('Number of Dataset you want to create :')
n = input()
print('Number of generated random integer in each DATASET:')
num = input()
print('Enter the path of your directory [DEFAULT is your current working directory]: ')
dirpath =  input()
if len(dirpath)==0:
    dirpath = str(os.getcwd())
print('Enter the name of dataset directory [DEFAULT is "GENERATED DATA(timestamp)"]: ')
dirname =  input()
timestamp = strftime("%d-%m-%Y , %H-%M")
if len(dirname)==0:
    dirname = 'GENERATED DATA on '+str(timestamp)+'  '+str(time.time())
print('Enter the name of your Datafile [Default is "DATASET[i]"]:')
fname = input()
if len(fname)==0:
      fname = 'DATASET'

      
path = str(dirpath)+'\\'+str(dirname) 
os.mkdir(path)
      
i = 0
while i< int(n):
    filename = str(fname)+str(int(i)+1)
    filepath = str(path)+'\\'+str(filename)+'.txt'
    f = open(str(filepath),"w")
    value = int.from_bytes(os.urandom(int(num)), byteorder="big")
    f.write(str(value))
    f.close()
    i+=1;

#METADATA CREATION-------------------------------------------------------------------------------------------------------------------------------------------------------------------

metadatapath = str(path)+'\\00. metadata.txt'
m = open(str(metadatapath), "w")
m.write('\n                          Path of the directory : '+str(dirpath))
m.write('\n                          Total no. of datasets : '+str(n))
m.write('\n No. of randomly generated data in each dataset : '+str(num))
m.write('\n                                     Time Stamp : '+str(time.ctime()))
m.write('\n                         Prefix of each dataset : '+str(fname))
m.write('\n   Randomly generated datasets are requested by : '+str(user)+'\n\n')
m.write('\n                      Datasets are generated by : RANDOM NUMBER DATASET GENERATOR')
m.write('\n                                        Version : 1.4')
m.write('\n                                     Created by : Amlan Saha Kundu')
m.close()

        

    
